musicip:
  container_name: "musicip"
  restart: unless-stopped
  image: justifiably/musicip
  ports:
    - 10002:10002
  volumes:
    - /srv/music/:/srv/music:ro                  # mount your music directory somewhere inside the container
    # - /int/musicip:/home/musicip/.MusicMagic   # to persist the db outside the container or edit mmm.ini


  